---
- name: Update all packages to the latest version
  apt:
    upgrade: yes

- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'software-properties-common', 'python3', 'python3-pip', 'python3-setuptools', 'libffi-dev', 'libssl-dev']

- name: Remove "python-configparser" package
  apt:
    name: python-configparser
    state: absent

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/raspbian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/raspbian buster stable
    state: present

- name: Update apt and install docker-ce
  apt:
    update_cache: yes
    name: docker-ce
    state: latest
    install_recommends: no

- name: Install Docker Module for Python
  pip:
    name: docker

- name: Add group "docker"
  group: name=docker

- name: Add the current user to the docker group
  user:
    name: pi
    groups: docker
    append: yes

- name: Install Docker Compose
  pip:
    name: docker-compose

- name: Ensures docker.service.d dir exists
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

# Override docker starting service to avoid conflicts with hosts flag https://docs.docker.com/config/daemon/
- name: Override docker service conf
  copy:
    src: docker.conf
    dest: '/etc/systemd/system/docker.service.d/docker.conf'

# Copy daemon.json file to enable remote access
- name: Copy daemon.json
  copy:
    src: daemon.json
    dest: '/etc/docker/daemon.json'

- name: Restart service docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker

- name: Create docker directory
  file:
    path: /home/pi/docker
    state: directory
    owner: pi
    group: docker

- name: Copy wordpress folder
  copy:
    src: wordpress
    dest: '/home/pi/docker'
    owner: pi
    group: docker

# Add host with docker machine ?
- name: Run docker compose
  docker_compose:
    docker_host: tcp://192.168.1.45:2375
    project_src: /home/pi/docker/wordpress
  register: output

# https://gist.github.com/calebbrewer/c41cab61216d8845b59fcc51f36343a7
# - name: Set Debian OS label
#  lineinfile:
#    path: /etc/os-release
#    state: present
#    regexp: '^ID=debian\s'
#  register: debianos
#
#- name: Replace Raspbian with Debian
#  lineinfile:
#    path: /etc/os-release
#    regexp: '^ID=raspbian'
#    line: ID=debian
#  when: debianos == 0
# - name: Run docker-compose for Wordpress
