version: '3.7'

services:
  db:
    image: tobi312/rpi-mariadb:10.3
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:5.4
    volumes:
      - ./wp-app:/var/www/html
      #- ./plugin-name/trunk:/var/www/html/wp-content/plugins/plugin-name
      #- ./theme-name/trunk:/var/www/html/wp-content/themes/theme-name
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  adminer:
    depends_on:
      - db
    image: adminer
    restart: always
    ports:
      - 8080:8080


networks:
  pureftpd:
    name: pureftpd

volumes:
    db_data: {}
#    ftpd_db_data: {}
